//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        public int Project_ID { get; set; }
        public string Project_Name { get; set; }
        public decimal User_ID { get; set; }
        public string Project_Address1 { get; set; }
        public string Preject_Address2 { get; set; }
        public string Project_City { get; set; }
        public string Project_State { get; set; }
        public string Project_Size { get; set; }
        public string Client_Name { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblProjToProd tblProjToProd { get; set; }
    }
}
