//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjToProd
    {
        public int Project_ID { get; set; }
        public int Product_ID { get; set; }
        public int Quantity { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblProject tblProject { get; set; }
    }
}
