//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProperty
    {
        public int Property_ID { get; set; }
        public string Property_Name { get; set; }
        public byte[] IsType { get; set; }
        public string IsTechSpec { get; set; }
    
        public virtual tblPropertyValue tblPropertyValue { get; set; }
        public virtual tblTechSpecFilter tblTechSpecFilter { get; set; }
        public virtual tblTypeFilter tblTypeFilter { get; set; }
    }
}
